### ISSUE TITLE
工作很棒，期待看到代码和详尽的readme。

### ISSUE THREAD

**Issue by PengboLiu** [wonderseen/OVC-MMT#1]

**Comment by wonderseen** [comment]
Hi, 感谢您的关注，仓库已更新。

由于object-level features文件大小超出网盘限制，需要您根据 [bottom_up_attention](https://github.com/peteanderson80/bottom-up-attention) 配置环境单独提取。

其他预处理数据可直接下载，或者可以使用 [scripts](https://github.com/wonderseen/OVC-MMT/tree/main/scripts) 中的脚本重新提取。如有其他疑问，欢迎补充。
